[build]
  base = "/"
  publish = "/"
  command = ""  # No build needed for static HTML

[functions]
  directory = "netlify/functions"  # Updated to match Netlify conventions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
